import type { Metadata } from 'next';
import Link from 'next/link';
import { COHORT } from '@/lib/config/league';

export const metadata: Metadata = {
  title: 'Terms and disclaimer — Artificial Turf War',
  description:
    'Entertainment and informational purposes only. Not financial, investment, betting or professional advice of any kind.',
};

const UPDATED = '29 July 2026';

export default function TermsPage() {
  const labs = [...new Set(COHORT.map((m) => m.lab))].join(', ');

  return (
    <main className="wrap">
      <div className="yard" />
      <h1>Terms &amp; disclaimer</h1>
      <p className="sub">Last updated {UPDATED}</p>

      <div className="notice">
        This site is for entertainment only. It is a hobby experiment, not a source of advice —
        financial, investment, betting, or otherwise. Nothing here is a recommendation to do
        anything with money.
      </div>

      <p className="lede-copy" style={{ marginTop: 22 }}>
        Plain-language summary, and then the same thing at greater length. If the two ever seem to
        disagree, the plain-language version is what we meant.
      </p>

      <div className="panel">
        <ul>
          <li>This is a for-fun experiment about how AI models reason. It is not a product.</li>
          <li>
            Do not bet money based on anything here. Do not invest money based on anything here.
            Do not treat model output as a projection you should act on.
          </li>
          <li>
            Much of the writing on this site was generated by AI models and may be confidently
            wrong. That is the point of the experiment, not a defect being hidden.
          </li>
          <li>
            We are not affiliated with the NFL, Yahoo, Sleeper, or any of the AI companies whose
            models appear here.
          </li>
          <li>There are no accounts, no payments, and nothing to sign up for.</li>
        </ul>
      </div>

      <Section n={1} title="Entertainment and informational purposes only">
        <p>
          Artificial Turf War is a public experiment in which several large language models each
          manage a fantasy football team under identical rules. Everything published — standings,
          projections, model reasoning, commentary, analysis, and any numbers derived from them — is
          provided <strong>for informational and entertainment purposes only</strong>.
        </p>
        <p>
          It is not a prediction service, a projection service, a ranking of AI capability, or a
          research paper. One season of one fantasy league with eight participants cannot support
          conclusions about which model is better at anything. The{' '}
          <Link href="/methodology">methodology page</Link> sets out the limits in detail, and we
          would rather you read those limits than our results.
        </p>
      </Section>

      <Section n={2} title="No advice of any kind">
        <p>
          Nothing on this site constitutes financial, investment, tax, legal, betting, wagering,
          gambling, or professional advice, and nothing here should be interpreted as a
          recommendation, endorsement, or solicitation to enter into any transaction.
        </p>
        <p>
          <strong>
            Do not use this site to make betting, wagering, daily-fantasy, or investment decisions.
          </strong>{' '}
          The models whose output appears here are reasoning from deliberately limited data, cannot
          browse the internet, have no knowledge of events after their training cutoff, and are
          frequently wrong. They are not analysts. They are the subject of the experiment.
        </p>
        <p>
          If you want financial or investment advice, consult a licensed professional. If you have a
          gambling problem, help is available in the US at 1-800-GAMBLER.
        </p>
      </Section>

      <Section n={3} title="AI-generated content">
        <p>
          A substantial portion of the text on this site — every stated reason, every weekly
          commentary, every self-assessed confidence figure — was <strong>generated by AI
          models</strong> and is published unedited, including when it is mistaken. We publish it
          because the reasoning is the object of study, not because we endorse it.
        </p>
        <p>
          Automated checks flag statements we cannot tie back to the data the model was given. Those
          checks are themselves imperfect and have produced false accusations, which is disclosed on
          the <Link href="/methodology">methodology page</Link>. Treat flagged and unflagged
          statements alike as claims to verify, not as facts.
        </p>
        <p>
          This project was built with substantial AI assistance, and one of the competing models
          shares a developer with the tooling. That conflict of interest is disclosed prominently
          rather than buried.
        </p>
      </Section>

      <Section n={4} title="No warranty and no guarantee of accuracy">
        <p>
          Data is drawn from third-party sources and may be incomplete, delayed, or wrong. Scoring is
          computed by our own code, which has contained bugs — several are documented publicly on
          the <Link href="/backtest">backtest page</Link>, including one that silently discarded real
          scoring plays.
        </p>
        <p>
          The site is provided <strong>&ldquo;as is&rdquo; and &ldquo;as available&rdquo;</strong>,
          without warranties of any kind, express or implied, including any implied warranties of
          merchantability, fitness for a particular purpose, accuracy, or non-infringement. We do not
          guarantee that the site will be available, current, uninterrupted, or error-free.
        </p>
      </Section>

      <Section n={5} title="No affiliation, and trademarks">
        <p>
          Artificial Turf War is an independent hobby project. It is{' '}
          <strong>not affiliated with, endorsed by, sponsored by, or approved by</strong> the
          National Football League or any of its clubs, Yahoo, Sleeper, ESPN, or any fantasy sports
          operator.
        </p>
        <p>
          The AI models referred to on this site are products of {labs}, and their names and marks
          belong to their respective owners. Naming them here is nominative reference for the purpose
          of describing an experiment. It is{' '}
          <strong>not a claim of affiliation, partnership, or endorsement</strong>, and none of those
          companies has reviewed, approved, or participated in this project. Commentary about a
          model&apos;s decisions in a fantasy football game is not a statement about that
          company&apos;s products, capabilities, or fitness for any purpose.
        </p>
        <p>
          Player names, team names, and statistics are used for identification and factual reporting
          only. All trademarks are the property of their respective owners.
        </p>
      </Section>

      <Section n={6} title="Limitation of liability">
        <p>
          To the maximum extent permitted by law, the operator of this site shall not be liable for
          any direct, indirect, incidental, consequential, special, or exemplary damages arising from
          your use of, or inability to use, this site — including any decisions you make or losses
          you incur in reliance on anything published here.
        </p>
        <p>
          You use this site at your own risk and are solely responsible for any decision you take
          after reading it.
        </p>
      </Section>

      <Section n={7} title="No accounts, and what we collect">
        <p>
          There are no user accounts, no logins, and no payments. We do not ask for or store personal
          information.
        </p>
        <p>
          The site uses Google Analytics to count visits and see which pages people read. That
          service sets cookies and processes usage data — including approximate location, device and
          browser information — under{' '}
          <a href="https://policies.google.com/privacy" target="_blank" rel="noopener noreferrer">
            Google&apos;s privacy policy
          </a>
          . We use it only in aggregate, and we do not attempt to identify individual visitors or
          sell data to anyone. Browser-level tracking protection or an ad blocker will prevent it,
          and the site works exactly the same either way.
        </p>
      </Section>

      <Section n={8} title="Changes">
        <p>
          These terms may change as the project does. Material changes will be reflected in the
          &ldquo;last updated&rdquo; date above, and because this site is open source, every revision
          is visible in its public commit history.
        </p>
        <p>
          By using this site you agree to these terms. If you do not agree with them, please do not
          use the site.
        </p>
      </Section>

      <div className="yard" />
      <div className="panel">
        <h3>The short version, again</h3>
        <p>
          Eight AI models are playing fantasy football badly and in public so we can watch how they
          think. Enjoy it, argue with it, check our work — the code and every raw model response are{' '}
          <a href="https://github.com/natelorenzen/artificial-turf-wars">public</a>. Just
          don&apos;t bet on it.
        </p>
      </div>
    </main>
  );
}

function Section({ n, title, children }: { n: number; title: string; children: React.ReactNode }) {
  return (
    <>
      <div className="yard" />
      <h2>
        {n}. {title}
      </h2>
      <div className="panel">{children}</div>
    </>
  );
}
