/**
 * The bounded, identical memory block (SPEC §4.1b "Continuity").
 *
 * A manager that has forgotten its own plan is not managing — but appending full
 * history would degrade Grok 4.5 (500K) before the others (~1M), which is exactly
 * the asymmetry §8.1 forbids. So every model carries the same structure, capped at
 * the same budget:
 *
 *   - its own gameplan, verbatim, all season
 *   - its current roster, budget, and record
 *   - headline + closest_call from its last N decisions of the SAME type
 *   - a one-line season summary generated by code, never by a model
 */

import { LEAGUE } from '@/lib/config/league';

export interface GameplanSummary {
  positional_strategy: string;
  auction_stance: string;
  scarcity_read: string;
  risk_posture: string;
  waiver_philosophy: string;
}

export interface PriorDecision {
  week: number | null;
  headline: string | null;
  closest_call: string | null;
}

export interface MemoryInput {
  gameplan: GameplanSummary | null;
  roster: { name: string; position: string }[];
  faabRemaining: number | null;
  record: { allplayW: number; allplayL: number; cumPts: number; rank: number | null } | null;
  recent: PriorDecision[];
  /** Deterministic one-liner, e.g. "Through week 6: 4th on all-play, 612.4 points." */
  seasonSummary: string | null;
}

/** Per-field truncation keeps the block a fixed shape regardless of model verbosity. */
const LIMITS = { field: 400, headline: 200, closestCall: 300 };

function clip(text: string | null | undefined, max: number): string {
  if (!text) return '—';
  const flat = text.replace(/\s+/g, ' ').trim();
  return flat.length <= max ? flat : `${flat.slice(0, max - 1)}…`;
}

export function buildMemoryBlock(input: MemoryInput): string {
  const parts: string[] = ['=== YOUR MEMORY ==='];

  parts.push('\nYOUR PRE-SEASON GAMEPLAN (written by you in August):');
  if (input.gameplan) {
    parts.push(`  Positional strategy: ${clip(input.gameplan.positional_strategy, LIMITS.field)}`);
    parts.push(`  Auction stance:      ${clip(input.gameplan.auction_stance, LIMITS.field)}`);
    parts.push(`  Scarcity read:       ${clip(input.gameplan.scarcity_read, LIMITS.field)}`);
    parts.push(`  Risk posture:        ${clip(input.gameplan.risk_posture, LIMITS.field)}`);
    parts.push(`  Waiver philosophy:   ${clip(input.gameplan.waiver_philosophy, LIMITS.field)}`);
  } else {
    parts.push('  (not yet written)');
  }

  parts.push('\nYOUR TEAM:');
  parts.push(
    `  Roster (${input.roster.length}/${LEAGUE.rosterSize}): ${
      input.roster.length > 0
        ? input.roster.map((p) => `${p.name} (${p.position})`).join(', ')
        : 'empty'
    }`,
  );
  parts.push(`  FAAB remaining: ${input.faabRemaining === null ? '—' : `$${input.faabRemaining}`}`);
  parts.push(
    `  Record: ${
      input.record
        ? `${input.record.allplayW}-${input.record.allplayL} all-play, ${input.record.cumPts} points${
            input.record.rank ? `, ${ordinal(input.record.rank)} of ${LEAGUE.teams}` : ''
          }`
        : 'no games played'
    }`,
  );

  parts.push(`\nYOUR LAST ${LEAGUE.memoryRecentDecisions} DECISIONS OF THIS TYPE:`);
  const recent = input.recent.slice(0, LEAGUE.memoryRecentDecisions);
  if (recent.length === 0) {
    parts.push('  (none yet)');
  } else {
    for (const d of recent) {
      parts.push(`  Week ${d.week ?? '—'}: ${clip(d.headline, LIMITS.headline)}`);
      parts.push(`    Closest call: ${clip(d.closest_call, LIMITS.closestCall)}`);
    }
  }

  parts.push(`\nSEASON TO DATE: ${input.seasonSummary ?? 'the season has not started'}`);
  parts.push('=== END MEMORY ===');

  return parts.join('\n');
}

export function ordinal(n: number): string {
  const s = ['th', 'st', 'nd', 'rd'];
  const v = n % 100;
  return n + (s[(v - 20) % 10] ?? s[v] ?? s[0]);
}

/** Deterministic season summary — code, never a model call (SPEC §8.4). */
export function seasonSummary(
  week: number,
  rank: number,
  teams: number,
  allplayW: number,
  allplayL: number,
  cumPts: number,
): string {
  return `Through week ${week}: ${ordinal(rank)} of ${teams} on all-play at ${allplayW}-${allplayL}, ${cumPts.toFixed(
    1,
  )} total points.`;
}
